### ISSUE TITLE
Feature Request: Recently Added or Updated folder

### ISSUE THREAD

**Issue by Hedders** [theypsilon/_arcade-organizer#53]
It seems like new arcade cores are released and existing ones are updated every week, which is wonderful but hard to keep track of.

It would be fantastic if we had a folder for cores that were added and/or updated recently (e.g. last 6 weeks or some such).

Regrettably I don't have the skills to code that myself, but maybe somebody here who does would be interested in implementing?

**Comment by therourke** [comment]
I would also absolutely love this, and I know there is some demand for it. Would be great to see releases by month (going back a year), and a 'new releases from last update' category. Something like that.

**Comment by Toryalai1** [comment]
One way of doing this is to check the <mratimestamp> tag in the MRA. The problem with that is that the core author sometimes forgets to update that tag...

**Comment by theypsilon** [comment]
It's a good suggestion but I don't think it belogs to the scope of the Arcade Organizer. With a broader scope it could also include other cores, and I'm pretty sure users will apprieciate that. I'm personally not gonna be able to code it because my backlog is already pretty big as it is, but hopefullly somebody else can do it. Closing it here, but thanks for the suggestion, maybe you could open a post about it in https://misterfpga.org/ and I'd give my support if necessary.

**Comment by BenPhegan** [comment]
For anyone that is still looking for something similar, I put something together that I find useful: https://github.com/BenPhegan/whats_new_mister

It can be run after any type of update, and will provide a list of new cores under a top-level "@WhatsNew" directory.

Hope it helps!
